name: Test and release

on:
  push:
    branches: [ "master" ]
    tags:
      - "*"
  pull_request:
    branches: [ "master" ]
  release:
    types:
      - published

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Test
        run: |
          ./gradlew build test

      - name: Publish to GitHub Packages
        if: github.event_name != 'pull_request'
        run: |
          ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
      if: startsWith(github.ref, 'refs/tags/')
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: ncipollo/release-action@v1
          with:
            generateReleaseNotes: true
